### ISSUE TITLE
PR Comment shows scan failed even when policy passed

### ISSUE THREAD

**Issue by mouradzadegun** [veracode/veracode-sca#16]
## Description
In success cases, when having scanner PR comment enabled and issue creation is disabled, post-scan comment shows `scan failed with exit code: <exit code>` no matter whether policy have passed or not.

## Screenshot
You can see here even though scan result exit with status code zero (0), the comment says scan have failed.
<img width="939" alt="Screenshot 2023-07-21 at 3 24 14 PM" src="https://github.com/veracode/veracode-sca/assets/57601790/9f2c69d3-30f3-498b-a7ca-ea2d8f7cb7e9">

## Reason
Following the comment logic shows in both failed or success case the comment output is `scan failed` in the following code blocks:
- Success case: https://github.com/veracode/veracode-sca/blob/main/src/srcclr.ts#L204-L208
- Failed case: https://github.com/veracode/veracode-sca/blob/main/src/srcclr.ts#L233-L235

**Comment by julz0815** [comment]
This is now fixed in v2.1.10, will close this issue
