### ISSUE TITLE
Veracode logo SVG in PR header returns 404

### ISSUE THREAD

**Issue by tkdoyle** [veracode/veracode-sca#21]
This .svg was working a few months ago, but is returning a 404 now. Can it be re-uploaded/the URL changed to a working version, so the logo is displayed in the PR header again?

https://github.com/veracode/veracode-sca/blob/91e334795877dc5522ee21f04a5aea342be40c31/src/srcclr.ts#L86C99-L86C123

<img width="1062" alt="image" src="https://github.com/veracode/veracode-sca/assets/41977301/9bbe924b-ea84-4710-a1d5-3af88b84ccb5">

**Comment by julz0815** [comment]
This is now fixe with v2.1.10, will close this issue
