### ISSUE TITLE
GitHub has deprecated Node 16, please update to Node 20

### ISSUE THREAD

**Issue by mattcollier** [veracode/veracode-sca#24]
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

https://github.com/veracode/veracode-sca/blob/0f32dfca4c613ff2a68fe52eacd4d340e47fd00b/action.yml#L56-L58

**Comment by julz0815** [comment]
This has been changed

**Comment by gman-wa** [comment]
@julz0815 - this needs a new release
