### ISSUE TITLE
/tmp/srcclr mktemp directory cleanup seems to fail if any errors occur during the action run

### ISSUE THREAD

**Issue by keaedwar** [veracode/veracode-sca#34]
Running the veracode-sca action failed most likely due to a /tmp directory cleanup or out of space condition on the GitHub Action Runner (since it's a shared resource) and the failure of the action to be able to handle cleaning up after the rje error.

Got the following error running the GitHub Action
```
Run veracode/veracode-sca@v2.1.10
Start command
curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan publish  
Error: stderr: Error: missing `server' JVM at `/tmp/srcclr/jre/lib/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components.
```
The action tries to be smart about clean up and reusing the previous unpacked version, but what seems to have occurred is that the jre directory was missing parts of previously unpacked gzip file, probably due to either /tmp running out of space or a /tmp cleanup removing files older than a specified time between the last action run and the current run.

The ci.sh code tries to be smart about cleaning up, but the missing code ended up leaving multiple srcclr.XXXXXX temp directories created by mktemp which never got cleaned up exacerbating the lack of space on /tmp.  Because the VERSION check file still existed in the /tmp/srcclr file, the shell script didn't think it needed to re-create the srcclr directory, so the situation continued to leave old srcclr.XXXXXX directories.

**Comment by julz0815** [comment]
Hi @keaedwar, this is not really a problem of the action, but how the images they run are configured. Usually the temp folder should be cleared for every run so nothing stays from a previous run.
I believe that is standard behaviour of the default images (like ubuntu-lastest) in GitHub as well.

The agent has to be extracted somewhere, if the image is caching everything that is happening on each image run, subsequently it will run out of memory.

You can also install the agent on the image and just use the srcclr command in the backgorund. But that would requeire to no use the action.

Clearing the temp dir or using another folder that will be cleared for each run is the best possible option here.

**Comment by keaedwar** [comment]
Ended up putting in a workaround to use RUNNER_TEMP instead of the /tmp as /tmp is a shared resource on the host and RUNNER_TEMP is a temporary directory on the runner.
